pybigquery/sqlalchemy_bigquery.py
Hi,
There has been a method name change. Currently the master doesn't work with e.g. Superset. There was also an error in the docs that has been fixed:
https://github.com/GoogleCloudPlatform/google-cloud-python/issues/4712
=> Client.list_dataset_tables(dataset) has been deprecated in favor of Client.list_tables(dataset)

pybigquery/sqlalchemy_bigquery.py
Auto generated sum/avg metrics in superset shows sum/avg expression as 
<pre>
AVG(`dataset`.`table`.`column`)
SUM(`dataset`.`table`.`column`)
</pre>
which is syntactically wrong in BQ.
To fix it have overwritten the visit_column method of SQLCompiler in BigQueryCompiler to set include_table parameter which is true by default to false. When this is done, the sum expression becomes
<pre>
SUM(`column`) which is correct.
</pre>
Could you please check if the fix is good and merge it.
=> Fix autogenerated metrics

setup.py
Hit error `UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in
position 780: ordinal not in range(128)` on py3.
Tested this solution against python 3.6 and 2.7
=> py3 compatible README.rst parsing

README.rst, dev_requirements.txt, pybigquery/parse_url.py, pybigquery/sqlalchemy_bigquery.py, setup.py, test/test_parse_url.py, test/test_sqlalchemy_bigquery.py
=> adding support for datasets and query arguments in connection string

pybigquery/sqlalchemy_bigquery.py, scripts/load_test_data.sh, test/test_sqlalchemy_bigquery.py
pybigquery does not return information about partitioning / cluster key on a bigquery table. this PR adds that support. so consumers like superset can use this information.
CC: @mistercrunch @tswast @mxmzdlv
=> return partition and clustering keys for tables through get_indexes

pybigquery/sqlalchemy_bigquery.py, test/test_sqlalchemy_bigquery.py
Currently, getColumns for repeated fields of type record only returns the top level column name.
Example, 
Instead of the returning something like,
```
array_field_name type:Record, mode:Repeated
array_field_name.foo : string
array_field_name.bar : string
```
getColumns() is returning 
```
array_field_name type:Record, mode:Repeated`
```
>> This PR is trying to address the above bug.
For type:record that is a non-repeated field, we will return something like this,
```
array_field_name type:Record, mode:NULLABLE
array_field_name.foo : string
array_field_name.bar : string
```
CC: @tswast @mistercrunch @mxmzdlv 
let me know if this is OK?
=> fix get column names for repeated fields of type record

pybigquery/sqlalchemy_bigquery.py, scripts/load_test_data.sh, test/test_sqlalchemy_bigquery.py
Map generic datatypes to bigquery datatypes.
With this patch, I was able to create tables with common types via pybigquery.
=> Add type compiler.

README.rst, pybigquery/sqlalchemy_bigquery.py, test/test_sqlalchemy_bigquery.py
To add metadata to a table:
```python
table = Table('mytable', ..., bigquery_description='my table description')
```
To add metadata to a column:
```python
Column('mycolumn', doc='my column description')
```
=> Support table and column metadata.

pybigquery/sqlalchemy_bigquery.py
This PR address the following error which we're seeing in Superset.
```403 Access Denied: BigQuery BigQuery: No OAuth token with Google Drive scope was found.```
Got inputs from https://github.com/googleapis/google-cloud-python/issues/3067#issuecomment-364103069
CC: @tswast @mistercrunch @mxmzdlv
=> Access to google drive source for federated queries made for bigquery

pybigquery/sqlalchemy_bigquery.py
BigQuery NUMERIC types don't have configurable scale or precision, so
override the default visitor to drop unused arguments.
=> Fix NUMERIC DDL representation.

pybigquery/sqlalchemy_bigquery.py
The default sqlalchemy `visit_insert` [compiler method](https://github.com/sqlalchemy/sqlalchemy/blob/5675345fc11966d449130ff4e4327a5a4bece0c2/lib/sqlalchemy/sql/compiler.py#L2828) compiles a correct BigQuery INSERT statement mostly out-of-the-box, it just needs to have this flag enabled.
=> Set BigQueryDialect.supports_multiline_insert to True

pybigquery/parse_url.py, pybigquery/sqlalchemy_bigquery.py, test/test_parse_url.py
=> Use the provided project_id when using a service account

pybigquery/sqlalchemy_bigquery.py, scripts/load_test_data.sh, test/test_sqlalchemy_bigquery.py
Fixes https://github.com/mxmzdlv/pybigquery/issues/51
=> Prefer explicitly provided dataset over default dataset in lookup

pybigquery/sqlalchemy_bigquery.py, test/test_sqlalchemy_bigquery.py
Use `TableReference` instead.
Issue: https://github.com/mxmzdlv/pybigquery/issues/58
=> ISSUE-58: Remove usage of deprecated Client.dataset

pybigquery/sqlalchemy_bigquery.py, test/test_sqlalchemy_bigquery.py
Fixes #39 - passes the "test case" I posted there and a number of internal queries I've tested with. Will look into adding a formal test in the next few days.
```
Print:
SELECT sum(sum(`test`.`val`)) OVER () AS `anon_1`, sum(CASE WHEN %(param_1)s THEN `test`.`val` END) AS `sum_1`, sum(sum(CASE WHEN %(param_2)s THEN `test`.`val` END)) OVER () AS `anon_2`
FROM `test`
Compile:
SELECT sum(sum(`test`.`val`)) OVER () AS `anon_1`, sum(CASE WHEN %(param_1)s THEN `test`.`val` END) AS `sum_1`, sum(sum(CASE WHEN %(param_2)s THEN `test`.`val` END)) OVER () AS `anon_2`
FROM `test`
Literal compile:
SELECT sum(sum(`test`.`val`)) OVER () AS `anon_1`, sum(CASE WHEN true THEN `test`.`val` END) AS `sum_1`, sum(sum(CASE WHEN true THEN `test`.`val` END)) OVER () AS `anon_2`
FROM `test`
Result:
((6, 6, 6),) …
```
=> Fix visit_label override to handle nested labels

pybigquery/sqlalchemy_bigquery.py, scripts/load_test_data.sh, test/test_sqlalchemy_bigquery.py
Issue: https://github.com/mxmzdlv/pybigquery/issues/60
**Major change:** in this change `get_table_names` will return **only** table names (without view names).
=> ISSUE-60: Implement get_view_names()

README.rst, pybigquery/sqlalchemy_bigquery.py, test/test_sqlalchemy_bigquery.py
This is a follow-on PR to https://github.com/mxmzdlv/pybigquery/pull/53 to implement the desired expanded project and dataset parsing behavior discussed during its review.
Tests have been updated and pass.
=> Allow use of schema argument for project and dataset

README.rst
fix typo: "SQLAchemy" -> "SQLAlchemy"
=> Update README.rst to fix typo: "SQLAchemy" -> "SQLAlchemy"

dev_requirements.txt, pybigquery/sqlalchemy_bigquery.py, scripts/load_test_data.sh, scripts/schema.json, test/test_sqlalchemy_bigquery.py
A fairly simple change to fetch descriptions during reflection. It just follows the directives set up by the docs https://docs.sqlalchemy.org/en/13/core/internals.html#sqlalchemy.engine.default.DefaultDialect.
=> Fetch table and column descriptions

pybigquery/sqlalchemy_bigquery.py, tests/unit/test_sqlalchemy_bigquery.py
=> fix: avoid 404 if dataset is deleted while listing tables or views

setup.py
Follow-up to https://github.com/googleapis/python-bigquery-sqlalchemy/pull/92 🦕
=> fix: correct classifiers in `setup.py`

setup.py, tests/system/conftest.py, tests/system/test_sqlalchemy_bigquery.py
This should avoid flakes. Also, adds a table expiration so that
if cleanup fails, BigQuery will still eventually remove the
table.
Fixes #111  🦕
=> test: use random suffix in DML test table

pybigquery/_helpers.py, tests/system/test_helpers.py, tests/unit/test_helpers.py
Adds system tests for greater assurance that these code paths function as expected.
Fixes #118  🦕
=> fix: use `project_id` property from service account credentials

pybigquery/sqlalchemy_bigquery.py, setup.py, testing/constraints-3.6.txt, tests/unit/conftest.py, tests/unit/fauxdbi.py, tests/unit/test_select.py
=> fix: Select expressions no-longer force use of labels
